build(pyproject.toml): gui, precommit, semver
Add GUI scripts to target from commandline (i.e. kkcalc), add pre-commit
hooks by default with dev branch install, and defaulted matching of the
beta branch releases to anything that is not main. Also added a tkinter
error message for instances where __main__.py is called, but PyQT6 is not
installed.

Additionally added a fetch-depth 0 to semver, so reversion SHAs can be found.

diff --git a/.github/workflows/semver.yml b/.github/workflows/semver.yml
--- a/.github/workflows/semver.yml
+++ b/.github/workflows/semver.yml
@@ -75,6 +75,18 @@ jobs:
         shell: bash
         run: |
           echo "Python SemVer pre-release?: $prerelease"
+
+      - name: Display Ref Info
+        shell: bash
+        run: |
+          echo "GitHub Ref: ${{ github.ref }}"
+          echo "GitHub Ref Name: ${{ github.ref_name }}"
+          echo "GitHub Commit SHA: ${{ github.sha }}"
+          echo "GitHub Event Name: ${{ github.event_name }}"
+          echo "PR GitHub Base Ref (PR Destination): ${{ github.base_ref }}"
+          echo "PR GitHub Head Ref (PR Source): ${{ github.head_ref }}"
+          echo "PR Source URL: ${{ github.event.pull_request.head.repo.html_url }}"
+
       # Note: We checkout the repository at the branch that triggered the workflow
       # with the entire history to ensure to match PSR's release branch detection
       # and history evaluation.
@@ -83,65 +95,54 @@ jobs:
       # prevents accidentally releasing un-evaluated changes.
       - name: Setup | Checkout Repository on Release Branch
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          persist-credentials: true
+          token: ${{ secrets.GITHUB_TOKEN }}
+          fetch-tags: true # Ensure tags are fetched for semantic-release
+          show-progress: true
+
+          # Need to checkout a branch, so that semver can appropriately do the release.
+          # Using the base_ref for pull requests, and ref for pushes/dispatches.
+          ref: ${{ ( github.event_name == 'pull_request' && github.base_ref) || github.ref }}
+
+          # ref: ${{ github.sha}} # Should this be github.head_ref || github.ref_name ?
+          # ref: ${{ github.sha }}
+          # ref: ${{ github.head_ref || github.sha || github.ref_name }}
+          # repository: ${{ github.repository }}
+
         # with:
           # ref: ${{ github.head_ref || github.ref }}
           # fetch-depth: 0
 
+      # REMOVED: As cannot run permissions conditionally.
+      # Because a checked out PR has a detached HEAD, we need to merge the PR changes
+      # manually to the target branch to ensure the correct code is present for the release.
+      # - name: Security | Ensure PR only has read privelages
+      #   if: ${{ github.event_name == 'pull_request' }}
+      #   run: |
+      #     echo "Ensuring GITHUB_TOKEN cannot write to repository"
+      #     GIT_TERMINAL_PROMPT=0 git push --dry-run &>/dev/null
+
+      - name: Setup | Merge PR to Target on PR Event
+        if: ${{ github.event_name == 'pull_request' }}
+        run: |
+          git remote -vv
+          git remote add origin-pr "${{ github.event.pull_request.head.repo.html_url }}"
+          git fetch origin-pr
+          git merge ${{ github.event.pull_request.head.sha }} --no-edit
+
       - name: Setup | Force release branch to be at workflow sha
+        if : ${{ github.event_name != 'pull_request' }}
         run: |
           git reset --hard ${{ github.sha }}
+        # Add an extra fetch step to make sure we have all history for semantic-release to evaluate.
+        # This was an error with the SHA: f80e68723d6de2358700ed773f3ba9073723bdb8 which was a revert.
 
-      # This code was originally in python-semantic-release 10.2.0 but does not appear in
-      # newer 10.5.2 version.
-      # https://python-semantic-release.readthedocs.io/en/latest/configuration/automatic-releases/github-actions.html
-      # - name: Evaluate | Verify upstream has NOT changed
-      #   # Last chance to abort before causing an error as another PR/push was applied to
-      #   # the upstream branch while this workflow was running. This is important
-      #   # because we are committing a version change (--commit). You may omit this step
-      #   # if you have 'commit: false' in your configuration.
-      #   #
-      #   # You may consider moving this to a repo script and call it from this step instead
-      #   # of writing it in-line.
-      #   shell: bash
-      #   if: ${{ github.event_name != 'workflow_dispatch' }}
-      #   run: |
-      #     set +o pipefail
 
-      #     UPSTREAM_BRANCH_NAME="$(git status -sb | head -n 1 | cut -d' ' -f2 | grep -E '\.{3}' | cut -d'.' -f4)"
-      #     printf '%s\n' "Upstream branch name: $UPSTREAM_BRANCH_NAME"
 
-      #     set -o pipefail
-
-      #     if [ -z "$UPSTREAM_BRANCH_NAME" ]; then
-      #         printf >&2 '%s\n' "::error::Unable to determine upstream branch name!"
-      #         exit 1
-      #     fi
-
-      #     git fetch "${UPSTREAM_BRANCH_NAME%%/*}"
-
-      #     if ! UPSTREAM_SHA="$(git rev-parse "$UPSTREAM_BRANCH_NAME")"; then
-      #         printf >&2 '%s\n' "::error::Unable to determine upstream branch sha!"
-      #         exit 1
-      #     fi
-
-      #     HEAD_SHA="$(git rev-parse HEAD)"
-
-      #     if [ "$HEAD_SHA" != "$UPSTREAM_SHA" ]; then
-      #         printf >&2 '%s\n' "[HEAD SHA] $HEAD_SHA != $UPSTREAM_SHA [UPSTREAM SHA]"
-      #         printf >&2 '%s\n' "::error::Upstream has changed, aborting release..."
-      #         exit 1
-      #     fi
-
-      #     printf '%s\n' "Verified upstream branch has not changed, continuing with release..."
-
-      # # - name: Delete Previous | Distribution Artifacts
-      # #   uses: actions/delete-artifact@v4 ???
-      # #   with:
-      # #     name: distribution-artifacts
-      # #     path: dist
-
-      # Either get or generate the GUI artefacts if requested
-      - name: Action | Download GUI Artefacts
+      # Either get or generate the GUI artifacts if requested
+      - name: Action | Download GUI Artifacts
         id: gui-download
         if: ${{ github.event == 'workflow_call' && github.event.inputs.gui-artifacts != '' }}
         uses: actions/download-artifact@v5
@@ -195,7 +196,10 @@ jobs:
           prerelease_token: ${{ env.prerelease_token }}
           changelog: true
           verbosity: 2
-          no_operation_mode: ${{ github.repository_owner != 'xraysoftmat' && github.repository_owner != 'benajamin'}}
+          # Do not actually perform any release actions if:
+          # 1. Not the main repository owner
+          # 2. This is a pull request event - the release should only occur on push to main/release branches
+          no_operation_mode: ${{ (github.repository_owner != 'xraysoftmat' && github.repository_owner != 'benajamin') || github.event_name == 'pull_request' }}
 
       - name: Env | Check if released and log conditionals
         id: is_released
@@ -204,7 +208,8 @@ jobs:
           echo "Ownership: ${{ github.repository_owner }} ; ${{ github.repository_owner == 'xraysoftmat' || github.repository_owner == 'benajamin' }}"
           echo "Released: ${{ steps.release.outputs.released }}"
           echo "Branch: ${{ github.ref }}; ${{ github.ref == 'refs/heads/main' }}"
-          echo "released=${{ steps.release.outcome && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/v2') && steps.release.outputs.released && (github.repository_owner == 'xraysoftmat' || github.repository_owner == 'benajamin') && steps.release.outcome == 'success' }}" >> "$GITHUB_OUTPUT"
+          echo "Push: ${{ github.event_name }} ; ${{ github.event_name == 'push' }}"
+          echo "released=${{ github.event_name == 'push' && steps.release.outcome && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/v2') && steps.release.outputs.released && (github.repository_owner == 'xraysoftmat' || github.repository_owner == 'benajamin') && steps.release.outcome == 'success' }}" >> "$GITHUB_OUTPUT"
 
       - name: Display | Release Information
         if: |
@@ -321,3 +326,54 @@ jobs:
         uses: pypa/gh-action-pypi-publish@release/v1
         with:
           packages-dir: kkcalc/dist
+
+
+
+      # This code was originally in python-semantic-release 10.2.0 but does not appear in
+      # newer 10.5.2 version. This would occur before the semantic release step.
+      # https://python-semantic-release.readthedocs.io/en/latest/configuration/automatic-releases/github-actions.html
+      # - name: Evaluate | Verify upstream has NOT changed
+      #   # Last chance to abort before causing an error as another PR/push was applied to
+      #   # the upstream branch while this workflow was running. This is important
+      #   # because we are committing a version change (--commit). You may omit this step
+      #   # if you have 'commit: false' in your configuration.
+      #   #
+      #   # You may consider moving this to a repo script and call it from this step instead
+      #   # of writing it in-line.
+      #   shell: bash
+      #   if: ${{ github.event_name != 'workflow_dispatch' }}
+      #   run: |
+      #     set +o pipefail
+
+      #     UPSTREAM_BRANCH_NAME="$(git status -sb | head -n 1 | cut -d' ' -f2 | grep -E '\.{3}' | cut -d'.' -f4)"
+      #     printf '%s\n' "Upstream branch name: $UPSTREAM_BRANCH_NAME"
+
+      #     set -o pipefail
+
+      #     if [ -z "$UPSTREAM_BRANCH_NAME" ]; then
+      #         printf >&2 '%s\n' "::error::Unable to determine upstream branch name!"
+      #         exit 1
+      #     fi
+
+      #     git fetch "${UPSTREAM_BRANCH_NAME%%/*}"
+
+      #     if ! UPSTREAM_SHA="$(git rev-parse "$UPSTREAM_BRANCH_NAME")"; then
+      #         printf >&2 '%s\n' "::error::Unable to determine upstream branch sha!"
+      #         exit 1
+      #     fi
+
+      #     HEAD_SHA="$(git rev-parse HEAD)"
+
+      #     if [ "$HEAD_SHA" != "$UPSTREAM_SHA" ]; then
+      #         printf >&2 '%s\n' "[HEAD SHA] $HEAD_SHA != $UPSTREAM_SHA [UPSTREAM SHA]"
+      #         printf >&2 '%s\n' "::error::Upstream has changed, aborting release..."
+      #         exit 1
+      #     fi
+
+      #     printf '%s\n' "Verified upstream branch has not changed, continuing with release..."
+
+      # # - name: Delete Previous | Distribution Artifacts
+      # #   uses: actions/delete-artifact@v4 ???
+      # #   with:
+      # #     name: distribution-artifacts
+      # #     path: dist
